### ISSUE TITLE
Colours do not look right?

### ISSUE THREAD

**Issue by Marcel-Robitaille** [alexanderjeurissen/dotfiles#3]
I have installed the gotham theme but the colours in the tmux bar are all wrong. How did you get them to look so good? I am using gnome-terminal.

Edit: added scrot.
![](http://i.imgur.com/Nw3J6X7.png)

**Comment by alexanderjeurissen** [comment]
@Marcel-Robitaille apologies for responding so late, I currently no longer use the Gotham theme nor do I use tmux. I currently use neovim terminal splits and vim sessions for that.

I'll update the screenshots and readme soon to reflect that.
