### ISSUE TITLE
Icons Tmux

### ISSUE THREAD

**Issue by Waldemar-Dassler** [alexanderjeurissen/dotfiles#8]
I don't understand, how you add icons to tmux. I added characters from mac but look like not good. I need transparent icons. Maybe you can help me?

**Comment by alexanderjeurissen** [comment]
I think I can, make sure you use a nice monospaced patched font.

In my screenshots I use SauceCodePro which is a patched version of the SourceCode pro font.
have a look at: https://github.com/ryanoasis/nerd-fonts

To download the exact font that I'm using (which guarantees the icons look similar) download one compatible with your system here:

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro/Regular/complete

Let me know if it works for you ;)

**Comment by Waldemar-Dassler** [comment]
![2017-05-12 13 30 17](https://cloud.githubusercontent.com/assets/25832802/25994653/5e3c59e8-3717-11e7-83ed-049903d9856e.png)

**Comment by Waldemar-Dassler** [comment]
1. I install FontAwesome.io
2. In iterm2 i choose second font 'fontAwesome' NON-ASII Font

and now its work for me! =)

**Comment by Waldemar-Dassler** [comment]
@alexanderjeurissen 
![2017-05-12 13 37 09](https://cloud.githubusercontent.com/assets/25832802/25994900/8b1261d2-3718-11e7-9dfd-7d0d071bef31.png)

**Comment by Waldemar-Dassler** [comment]
I did what you said and work it's fine =) thanks
